# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Classifies the address type (<i>Home</i>, <i>Business</i>, <i>Billing</i>,
  # <i>Shipping</i>)
  class AddressTypesEnum
    ADDRESS_TYPES_ENUM = [
      # TODO: Write general description for RESIDENTIAL
      RESIDENTIAL = 'RESIDENTIAL'.freeze,

      # TODO: Write general description for BUSINESS
      BUSINESS = 'BUSINESS'.freeze,

      # TODO: Write general description for MAILING
      MAILING = 'MAILING'.freeze
    ].freeze
  end
end
