# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Determines whether the quote is automatically accepted or if a POST
  # utilizing the token for the quote is required.
  class AutoAcceptQuote < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Determines whether the quote is automatically accepted or if a POST
    # utilizing the token for the quote is required.
    # @return [Boolean]
    attr_accessor :auto_accept_quote

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['auto_accept_quote'] = 'autoAcceptQuote'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        auto_accept_quote
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(auto_accept_quote = nil)
      @auto_accept_quote = auto_accept_quote unless auto_accept_quote == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      auto_accept_quote =
        hash.key?('autoAcceptQuote') ? hash['autoAcceptQuote'] : SKIP

      # Create object from extracted values.
      AutoAcceptQuote.new(auto_accept_quote)
    end
  end
end
