# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Financial purpose of the bank account (<i>Savings</i>, <i>Investment</i>)
  class BankAccountTypesEnum
    BANK_ACCOUNT_TYPES_ENUM = [
      # TODO: Write general description for CHECKING
      CHECKING = 'CHECKING'.freeze,

      # TODO: Write general description for SAVINGS
      SAVINGS = 'SAVINGS'.freeze,

      # TODO: Write general description for MONEY_MARKET
      MONEY_MARKET = 'MONEY_MARKET'.freeze
    ].freeze
  end
end
