# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Account ownership type
  class BankAccountOwnership < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account ownership types
    # @return [BankAccountOwnershipTypesEnum]
    attr_accessor :bank_account_ownership_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bank_account_ownership_type'] = 'bankAccountOwnershipType'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        bank_account_ownership_type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(bank_account_ownership_type = nil)
      unless bank_account_ownership_type == SKIP
        @bank_account_ownership_type =
          bank_account_ownership_type
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      bank_account_ownership_type =
        hash.key?('bankAccountOwnershipType') ? hash['bankAccountOwnershipType'] : SKIP

      # Create object from extracted values.
      BankAccountOwnership.new(bank_account_ownership_type)
    end
  end
end
