# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Account ownership types
  class BankAccountOwnershipTypesEnum
    BANK_ACCOUNT_OWNERSHIP_TYPES_ENUM = [
      # TODO: Write general description for PERSONAL
      PERSONAL = 'PERSONAL'.freeze,

      # TODO: Write general description for BUSINESS
      BUSINESS = 'BUSINESS'.freeze
    ].freeze
  end
end
