# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Classifies account field types
  class BankAccountFieldTypesEnum
    BANK_ACCOUNT_FIELD_TYPES_ENUM = [
      # TODO: Write general description for BANK_ACH_ABA
      BANK_ACH_ABA = 'BANK_ACH_ABA'.freeze,

      # TODO: Write general description for BANK_BBAN
      BANK_BBAN = 'BANK_BBAN'.freeze,

      # TODO: Write general description for BANK_BRANCH_CODE
      BANK_BRANCH_CODE = 'BANK_BRANCH_CODE'.freeze,

      # TODO: Write general description for BANK_BSB_CODE
      BANK_BSB_CODE = 'BANK_BSB_CODE'.freeze,

      # TODO: Write general description for BANK_CITY
      BANK_CITY = 'BANK_CITY'.freeze,

      # TODO: Write general description for BANK_CLABE
      BANK_CLABE = 'BANK_CLABE'.freeze,

      # TODO: Write general description for BANK_CODE
      BANK_CODE = 'BANK_CODE'.freeze,

      # TODO: Write general description for BANK_CURP
      BANK_CURP = 'BANK_CURP'.freeze,

      # TODO: Write general description for BANK_IBAN
      BANK_IBAN = 'BANK_IBAN'.freeze,

      # TODO: Write general description for BANK_NAME
      BANK_NAME = 'BANK_NAME'.freeze,

      # TODO: Write general description for BANK_NON_SWIFT_BIC
      BANK_NON_SWIFT_BIC = 'BANK_NON_SWIFT_BIC'.freeze,

      # TODO: Write general description for BANK_NUBAN
      BANK_NUBAN = 'BANK_NUBAN'.freeze,

      # TODO: Write general description for BANK_PHONE_NUMBER
      BANK_PHONE_NUMBER = 'BANK_PHONE_NUMBER'.freeze,

      # TODO: Write general description for BANK_POSTAL_CODE
      BANK_POSTAL_CODE = 'BANK_POSTAL_CODE'.freeze,

      # TODO: Write general description for BANK_REGION
      BANK_REGION = 'BANK_REGION'.freeze,

      # TODO: Write general description for BANK_RFC
      BANK_RFC = 'BANK_RFC'.freeze,

      # TODO: Write general description for BANK_SORT_CODE
      BANK_SORT_CODE = 'BANK_SORT_CODE'.freeze,

      # TODO: Write general description for BANK_STREET_ADDRESS
      BANK_STREET_ADDRESS = 'BANK_STREET_ADDRESS'.freeze,

      # TODO: Write general description for BANK_SWIFT_BIC
      BANK_SWIFT_BIC = 'BANK_SWIFT_BIC'.freeze,

      # TODO: Write general description for BANK_TRANSIT_CODE
      BANK_TRANSIT_CODE = 'BANK_TRANSIT_CODE'.freeze,

      # TODO: Write general description for BENEFICIARY_ACCOUNT_NUMBER
      BENEFICIARY_ACCOUNT_NUMBER = 'BENEFICIARY_ACCOUNT_NUMBER'.freeze,

      # TODO: Write general description for BENEFICIARY_PHONE_NUMBER
      BENEFICIARY_PHONE_NUMBER = 'BENEFICIARY_PHONE_NUMBER'.freeze,

      # TODO: Write general description for BENEFICIARY_TAX_ID
      BENEFICIARY_TAX_ID = 'BENEFICIARY_TAX_ID'.freeze,

      # TODO: Write general description for BENEFICIARY_NAME
      BENEFICIARY_NAME = 'BENEFICIARY_NAME'.freeze,

      # TODO: Write general description for BANK_BRANCH_NAME
      BANK_BRANCH_NAME = 'BANK_BRANCH_NAME'.freeze,

      # TODO: Write general description for BANK_PURPOSE_OF_PAYMENT_CODE
      BANK_PURPOSE_OF_PAYMENT_CODE = 'BANK_PURPOSE_OF_PAYMENT_CODE'.freeze,

      # TODO: Write general description for BANK_VALUE_ADD_TAX
      BANK_VALUE_ADD_TAX = 'BANK_VALUE_ADD_TAX'.freeze
    ].freeze
  end
end
