# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Current verification status type of the bank account
  class BankAccountStatusTypesEnum
    BANK_ACCOUNT_STATUS_TYPES_ENUM = [
      # TODO: Write general description for DELETED
      DELETED = 'DELETED'.freeze,

      # TODO: Write general description for ACTIVE
      ACTIVE = 'ACTIVE'.freeze,

      # TODO: Write general description for PENDING_VERIFICATION
      PENDING_VERIFICATION = 'PENDING_VERIFICATION'.freeze
    ].freeze
  end
end
