# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # BusinessType Model.
  class BusinessType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Type of business (<i>Corporation</i> or <i>Partnership</i>)
    # @return [BusinessTypesEnum]
    attr_accessor :business_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['business_type'] = 'businessType'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        business_type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(business_type = nil)
      @business_type = business_type unless business_type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      business_type = hash.key?('businessType') ? hash['businessType'] : SKIP

      # Create object from extracted values.
      BusinessType.new(business_type)
    end
  end
end
