# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Role of the user within the business
  class BusinessContactRoleEnum
    BUSINESS_CONTACT_ROLE_ENUM = [
      # TODO: Write general description for OWNER
      OWNER = 'OWNER'.freeze,

      # TODO: Write general description for MANAGER
      MANAGER = 'MANAGER'.freeze,

      # TODO: Write general description for PARTNER
      PARTNER = 'PARTNER'.freeze,

      # TODO: Write general description for OTHER
      OTHER = 'OTHER'.freeze
    ].freeze
  end
end
