# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Type of business (<i>Corporation</i> or <i>Partnership</i>)
  class BusinessTypesEnum
    BUSINESS_TYPES_ENUM = [
      # TODO: Write general description for CORPORATION
      CORPORATION = 'CORPORATION'.freeze,

      # TODO: Write general description for PARTNERSHIP_DBA
      PARTNERSHIP_DBA = 'PARTNERSHIP_DBA'.freeze
    ].freeze
  end
end
