# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Card number using PAN truncation
  class CardMaskedPan < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Masked card number with only the first 6 and last 4 digits visible
    # @return [String]
    attr_accessor :card_number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_number'] = 'cardNumber'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        card_number
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(card_number = nil)
      @card_number = card_number unless card_number == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_number = hash.key?('cardNumber') ? hash['cardNumber'] : SKIP

      # Create object from extracted values.
      CardMaskedPan.new(card_number)
    end
  end
end
