# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Type of personalization for the prepaid card
  class CardPersonalizationType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Specifies a card is <i>Personalized</i> or <i>Non-personalized</i> (i.e.,
    # issued to Preferred Customer)
    # @return [PrepaidCardPersonalizationTypesEnum]
    attr_accessor :card_personalization

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_personalization'] = 'cardPersonalization'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        card_personalization
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(card_personalization = nil)
      @card_personalization = card_personalization unless card_personalization == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_personalization =
        hash.key?('cardPersonalization') ? hash['cardPersonalization'] : SKIP

      # Create object from extracted values.
      CardPersonalizationType.new(card_personalization)
    end
  end
end
