# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Major credit card network
  class CardNetwork < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Major credit card network types
    # @return [CardNetworkTypesEnum]
    attr_accessor :card_network

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_network'] = 'cardNetwork'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        card_network
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(card_network = nil)
      @card_network = card_network unless card_network == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_network = hash.key?('cardNetwork') ? hash['cardNetwork'] : SKIP

      # Create object from extracted values.
      CardNetwork.new(card_network)
    end
  end
end
