# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Major credit card network types
  class CardNetworkTypesEnum
    CARD_NETWORK_TYPES_ENUM = [
      # TODO: Write general description for VISA
      VISA = 'VISA'.freeze,

      # TODO: Write general description for MASTER_CARD
      MASTER_CARD = 'MASTER_CARD'.freeze
    ].freeze
  end
end
