# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Unique value provided by the client for the payment, utilized for reference
  # and de-duplication.
  class ClientPaymentId < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique value provided by the client for the payment.
    # @return [String]
    attr_accessor :client_payment_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['client_payment_id'] = 'clientPaymentId'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        client_payment_id
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(client_payment_id = nil)
      @client_payment_id = client_payment_id unless client_payment_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      client_payment_id =
        hash.key?('clientPaymentId') ? hash['clientPaymentId'] : SKIP

      # Create object from extracted values.
      ClientPaymentId.new(client_payment_id)
    end
  end
end
