# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Unique value provided by the client for the transfer, utilized for reference
  # and deduplication.
  class ClientTransferId < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique value provided by the client for the transfer.
    # @return [String]
    attr_accessor :client_transfer_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['client_transfer_id'] = 'clientTransferId'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        client_transfer_id
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(client_transfer_id = nil)
      @client_transfer_id = client_transfer_id unless client_transfer_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      client_transfer_id =
        hash.key?('clientTransferId') ? hash['clientTransferId'] : SKIP

      # Create object from extracted values.
      ClientTransferId.new(client_transfer_id)
    end
  end
end
