# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Two-digit country code for the object
  class Country < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Two-digit country code types
    # @return [CountryTypesEnum]
    attr_accessor :country

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['country'] = 'country'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(country = nil)
      @country = country unless country == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      country = hash.key?('country') ? hash['country'] : SKIP

      # Create object from extracted values.
      Country.new(country)
    end
  end
end
