# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Two-digit country code types
  class CountryTypesEnum
    COUNTRY_TYPES_ENUM = [
      # TODO: Write general description for AD
      AD = 'AD'.freeze,

      # TODO: Write general description for AE
      AE = 'AE'.freeze,

      # TODO: Write general description for AF
      AF = 'AF'.freeze,

      # TODO: Write general description for AG
      AG = 'AG'.freeze,

      # TODO: Write general description for AI
      AI = 'AI'.freeze,

      # TODO: Write general description for AL
      AL = 'AL'.freeze,

      # TODO: Write general description for AM
      AM = 'AM'.freeze,

      # TODO: Write general description for AN
      AN = 'AN'.freeze,

      # TODO: Write general description for AO
      AO = 'AO'.freeze,

      # TODO: Write general description for AQ
      AQ = 'AQ'.freeze,

      # TODO: Write general description for AR
      AR = 'AR'.freeze,

      # TODO: Write general description for AS
      AS = 'AS'.freeze,

      # TODO: Write general description for AT
      AT = 'AT'.freeze,

      # TODO: Write general description for AU
      AU = 'AU'.freeze,

      # TODO: Write general description for AW
      AW = 'AW'.freeze,

      # TODO: Write general description for AX
      AX = 'AX'.freeze,

      # TODO: Write general description for AZ
      AZ = 'AZ'.freeze,

      # TODO: Write general description for BA
      BA = 'BA'.freeze,

      # TODO: Write general description for BB
      BB = 'BB'.freeze,

      # TODO: Write general description for BD
      BD = 'BD'.freeze,

      # TODO: Write general description for BE
      BE = 'BE'.freeze,

      # TODO: Write general description for BF
      BF = 'BF'.freeze,

      # TODO: Write general description for BG
      BG = 'BG'.freeze,

      # TODO: Write general description for BH
      BH = 'BH'.freeze,

      # TODO: Write general description for BI
      BI = 'BI'.freeze,

      # TODO: Write general description for BJ
      BJ = 'BJ'.freeze,

      # TODO: Write general description for BL
      BL = 'BL'.freeze,

      # TODO: Write general description for BM
      BM = 'BM'.freeze,

      # TODO: Write general description for BN
      BN = 'BN'.freeze,

      # TODO: Write general description for BO
      BO = 'BO'.freeze,

      # TODO: Write general description for BQ
      BQ = 'BQ'.freeze,

      # TODO: Write general description for BR
      BR = 'BR'.freeze,

      # TODO: Write general description for BS
      BS = 'BS'.freeze,

      # TODO: Write general description for BT
      BT = 'BT'.freeze,

      # TODO: Write general description for BV
      BV = 'BV'.freeze,

      # TODO: Write general description for BW
      BW = 'BW'.freeze,

      # TODO: Write general description for BY
      BY = 'BY'.freeze,

      # TODO: Write general description for BZ
      BZ = 'BZ'.freeze,

      # TODO: Write general description for CA
      CA = 'CA'.freeze,

      # TODO: Write general description for CC
      CC = 'CC'.freeze,

      # TODO: Write general description for CD
      CD = 'CD'.freeze,

      # TODO: Write general description for CF
      CF = 'CF'.freeze,

      # TODO: Write general description for CG
      CG = 'CG'.freeze,

      # TODO: Write general description for CH
      CH = 'CH'.freeze,

      # TODO: Write general description for CI
      CI = 'CI'.freeze,

      # TODO: Write general description for CK
      CK = 'CK'.freeze,

      # TODO: Write general description for CL
      CL = 'CL'.freeze,

      # TODO: Write general description for CM
      CM = 'CM'.freeze,

      # TODO: Write general description for CN
      CN = 'CN'.freeze,

      # TODO: Write general description for CO
      CO = 'CO'.freeze,

      # TODO: Write general description for CR
      CR = 'CR'.freeze,

      # TODO: Write general description for CU
      CU = 'CU'.freeze,

      # TODO: Write general description for CV
      CV = 'CV'.freeze,

      # TODO: Write general description for CW
      CW = 'CW'.freeze,

      # TODO: Write general description for CX
      CX = 'CX'.freeze,

      # TODO: Write general description for CY
      CY = 'CY'.freeze,

      # TODO: Write general description for CZ
      CZ = 'CZ'.freeze,

      # TODO: Write general description for DE
      DE = 'DE'.freeze,

      # TODO: Write general description for DJ
      DJ = 'DJ'.freeze,

      # TODO: Write general description for DK
      DK = 'DK'.freeze,

      # TODO: Write general description for DM
      DM = 'DM'.freeze,

      # TODO: Write general description for DO
      DO = 'DO'.freeze,

      # TODO: Write general description for DZ
      DZ = 'DZ'.freeze,

      # TODO: Write general description for EC
      EC = 'EC'.freeze,

      # TODO: Write general description for EE
      EE = 'EE'.freeze,

      # TODO: Write general description for EG
      EG = 'EG'.freeze,

      # TODO: Write general description for EH
      EH = 'EH'.freeze,

      # TODO: Write general description for ER
      ER = 'ER'.freeze,

      # TODO: Write general description for ES
      ES = 'ES'.freeze,

      # TODO: Write general description for ET
      ET = 'ET'.freeze,

      # TODO: Write general description for FI
      FI = 'FI'.freeze,

      # TODO: Write general description for FJ
      FJ = 'FJ'.freeze,

      # TODO: Write general description for FK
      FK = 'FK'.freeze,

      # TODO: Write general description for FM
      FM = 'FM'.freeze,

      # TODO: Write general description for FO
      FO = 'FO'.freeze,

      # TODO: Write general description for FR
      FR = 'FR'.freeze,

      # TODO: Write general description for GA
      GA = 'GA'.freeze,

      # TODO: Write general description for GB
      GB = 'GB'.freeze,

      # TODO: Write general description for GD
      GD = 'GD'.freeze,

      # TODO: Write general description for GE
      GE = 'GE'.freeze,

      # TODO: Write general description for GF
      GF = 'GF'.freeze,

      # TODO: Write general description for GG
      GG = 'GG'.freeze,

      # TODO: Write general description for GH
      GH = 'GH'.freeze,

      # TODO: Write general description for GI
      GI = 'GI'.freeze,

      # TODO: Write general description for GL
      GL = 'GL'.freeze,

      # TODO: Write general description for GM
      GM = 'GM'.freeze,

      # TODO: Write general description for GN
      GN = 'GN'.freeze,

      # TODO: Write general description for GP
      GP = 'GP'.freeze,

      # TODO: Write general description for GQ
      GQ = 'GQ'.freeze,

      # TODO: Write general description for GR
      GR = 'GR'.freeze,

      # TODO: Write general description for GS
      GS = 'GS'.freeze,

      # TODO: Write general description for GT
      GT = 'GT'.freeze,

      # TODO: Write general description for GU
      GU = 'GU'.freeze,

      # TODO: Write general description for GW
      GW = 'GW'.freeze,

      # TODO: Write general description for GY
      GY = 'GY'.freeze,

      # TODO: Write general description for HK
      HK = 'HK'.freeze,

      # TODO: Write general description for HM
      HM = 'HM'.freeze,

      # TODO: Write general description for HN
      HN = 'HN'.freeze,

      # TODO: Write general description for HR
      HR = 'HR'.freeze,

      # TODO: Write general description for HT
      HT = 'HT'.freeze,

      # TODO: Write general description for HU
      HU = 'HU'.freeze,

      # TODO: Write general description for ID
      ID = 'ID'.freeze,

      # TODO: Write general description for IE
      IE = 'IE'.freeze,

      # TODO: Write general description for IL
      IL = 'IL'.freeze,

      # TODO: Write general description for IM
      IM = 'IM'.freeze,

      # TODO: Write general description for IN
      IN = 'IN'.freeze,

      # TODO: Write general description for IO
      IO = 'IO'.freeze,

      # TODO: Write general description for IQ
      IQ = 'IQ'.freeze,

      # TODO: Write general description for IR
      IR = 'IR'.freeze,

      # TODO: Write general description for IS
      IS = 'IS'.freeze,

      # TODO: Write general description for IT
      IT = 'IT'.freeze,

      # TODO: Write general description for JE
      JE = 'JE'.freeze,

      # TODO: Write general description for JM
      JM = 'JM'.freeze,

      # TODO: Write general description for JO
      JO = 'JO'.freeze,

      # TODO: Write general description for JP
      JP = 'JP'.freeze,

      # TODO: Write general description for KE
      KE = 'KE'.freeze,

      # TODO: Write general description for KG
      KG = 'KG'.freeze,

      # TODO: Write general description for KH
      KH = 'KH'.freeze,

      # TODO: Write general description for KI
      KI = 'KI'.freeze,

      # TODO: Write general description for KM
      KM = 'KM'.freeze,

      # TODO: Write general description for KN
      KN = 'KN'.freeze,

      # TODO: Write general description for KP
      KP = 'KP'.freeze,

      # TODO: Write general description for KR
      KR = 'KR'.freeze,

      # TODO: Write general description for KW
      KW = 'KW'.freeze,

      # TODO: Write general description for KY
      KY = 'KY'.freeze,

      # TODO: Write general description for KZ
      KZ = 'KZ'.freeze,

      # TODO: Write general description for LA
      LA = 'LA'.freeze,

      # TODO: Write general description for LB
      LB = 'LB'.freeze,

      # TODO: Write general description for LC
      LC = 'LC'.freeze,

      # TODO: Write general description for LI
      LI = 'LI'.freeze,

      # TODO: Write general description for LK
      LK = 'LK'.freeze,

      # TODO: Write general description for LR
      LR = 'LR'.freeze,

      # TODO: Write general description for LS
      LS = 'LS'.freeze,

      # TODO: Write general description for LT
      LT = 'LT'.freeze,

      # TODO: Write general description for LU
      LU = 'LU'.freeze,

      # TODO: Write general description for LV
      LV = 'LV'.freeze,

      # TODO: Write general description for LY
      LY = 'LY'.freeze,

      # TODO: Write general description for MA
      MA = 'MA'.freeze,

      # TODO: Write general description for MC
      MC = 'MC'.freeze,

      # TODO: Write general description for MD
      MD = 'MD'.freeze,

      # TODO: Write general description for ME
      ME = 'ME'.freeze,

      # TODO: Write general description for MF
      MF = 'MF'.freeze,

      # TODO: Write general description for MG
      MG = 'MG'.freeze,

      # TODO: Write general description for MH
      MH = 'MH'.freeze,

      # TODO: Write general description for MK
      MK = 'MK'.freeze,

      # TODO: Write general description for ML
      ML = 'ML'.freeze,

      # TODO: Write general description for MM
      MM = 'MM'.freeze,

      # TODO: Write general description for MN
      MN = 'MN'.freeze,

      # TODO: Write general description for MO
      MO = 'MO'.freeze,

      # TODO: Write general description for MP
      MP = 'MP'.freeze,

      # TODO: Write general description for MQ
      MQ = 'MQ'.freeze,

      # TODO: Write general description for MR
      MR = 'MR'.freeze,

      # TODO: Write general description for MS
      MS = 'MS'.freeze,

      # TODO: Write general description for MT
      MT = 'MT'.freeze,

      # TODO: Write general description for MU
      MU = 'MU'.freeze,

      # TODO: Write general description for MV
      MV = 'MV'.freeze,

      # TODO: Write general description for MW
      MW = 'MW'.freeze,

      # TODO: Write general description for MX
      MX = 'MX'.freeze,

      # TODO: Write general description for MY
      MY = 'MY'.freeze,

      # TODO: Write general description for MZ
      MZ = 'MZ'.freeze,

      # TODO: Write general description for NA
      NA = 'NA'.freeze,

      # TODO: Write general description for NC
      NC = 'NC'.freeze,

      # TODO: Write general description for NE
      NE = 'NE'.freeze,

      # TODO: Write general description for NF
      NF = 'NF'.freeze,

      # TODO: Write general description for NG
      NG = 'NG'.freeze,

      # TODO: Write general description for NI
      NI = 'NI'.freeze,

      # TODO: Write general description for NL
      NL = 'NL'.freeze,

      # TODO: Write general description for NO
      NO = 'NO'.freeze,

      # TODO: Write general description for NP
      NP = 'NP'.freeze,

      # TODO: Write general description for NR
      NR = 'NR'.freeze,

      # TODO: Write general description for NU
      NU = 'NU'.freeze,

      # TODO: Write general description for NZ
      NZ = 'NZ'.freeze,

      # TODO: Write general description for OM
      OM = 'OM'.freeze,

      # TODO: Write general description for PA
      PA = 'PA'.freeze,

      # TODO: Write general description for PE
      PE = 'PE'.freeze,

      # TODO: Write general description for PF
      PF = 'PF'.freeze,

      # TODO: Write general description for PG
      PG = 'PG'.freeze,

      # TODO: Write general description for PH
      PH = 'PH'.freeze,

      # TODO: Write general description for PK
      PK = 'PK'.freeze,

      # TODO: Write general description for PL
      PL = 'PL'.freeze,

      # TODO: Write general description for PM
      PM = 'PM'.freeze,

      # TODO: Write general description for PN
      PN = 'PN'.freeze,

      # TODO: Write general description for PR
      PR = 'PR'.freeze,

      # TODO: Write general description for PS
      PS = 'PS'.freeze,

      # TODO: Write general description for PT
      PT = 'PT'.freeze,

      # TODO: Write general description for PW
      PW = 'PW'.freeze,

      # TODO: Write general description for PY
      PY = 'PY'.freeze,

      # TODO: Write general description for QA
      QA = 'QA'.freeze,

      # TODO: Write general description for RE
      RE = 'RE'.freeze,

      # TODO: Write general description for RO
      RO = 'RO'.freeze,

      # TODO: Write general description for RS
      RS = 'RS'.freeze,

      # TODO: Write general description for RU
      RU = 'RU'.freeze,

      # TODO: Write general description for RW
      RW = 'RW'.freeze,

      # TODO: Write general description for SA
      SA = 'SA'.freeze,

      # TODO: Write general description for SB
      SB = 'SB'.freeze,

      # TODO: Write general description for SC
      SC = 'SC'.freeze,

      # TODO: Write general description for SD
      SD = 'SD'.freeze,

      # TODO: Write general description for SE
      SE = 'SE'.freeze,

      # TODO: Write general description for SG
      SG = 'SG'.freeze,

      # TODO: Write general description for SH
      SH = 'SH'.freeze,

      # TODO: Write general description for SI
      SI = 'SI'.freeze,

      # TODO: Write general description for SJ
      SJ = 'SJ'.freeze,

      # TODO: Write general description for SK
      SK = 'SK'.freeze,

      # TODO: Write general description for SL
      SL = 'SL'.freeze,

      # TODO: Write general description for SM
      SM = 'SM'.freeze,

      # TODO: Write general description for SN
      SN = 'SN'.freeze,

      # TODO: Write general description for SO
      SO = 'SO'.freeze,

      # TODO: Write general description for SR
      SR = 'SR'.freeze,

      # TODO: Write general description for SS
      SS = 'SS'.freeze,

      # TODO: Write general description for ST
      ST = 'ST'.freeze,

      # TODO: Write general description for SV
      SV = 'SV'.freeze,

      # TODO: Write general description for SX
      SX = 'SX'.freeze,

      # TODO: Write general description for SY
      SY = 'SY'.freeze,

      # TODO: Write general description for SZ
      SZ = 'SZ'.freeze,

      # TODO: Write general description for TC
      TC = 'TC'.freeze,

      # TODO: Write general description for TD
      TD = 'TD'.freeze,

      # TODO: Write general description for TF
      TF = 'TF'.freeze,

      # TODO: Write general description for TG
      TG = 'TG'.freeze,

      # TODO: Write general description for TH
      TH = 'TH'.freeze,

      # TODO: Write general description for TJ
      TJ = 'TJ'.freeze,

      # TODO: Write general description for TK
      TK = 'TK'.freeze,

      # TODO: Write general description for TL
      TL = 'TL'.freeze,

      # TODO: Write general description for TM
      TM = 'TM'.freeze,

      # TODO: Write general description for TN
      TN = 'TN'.freeze,

      # TODO: Write general description for TO
      TO = 'TO'.freeze,

      # TODO: Write general description for TR
      TR = 'TR'.freeze,

      # TODO: Write general description for TT
      TT = 'TT'.freeze,

      # TODO: Write general description for TV
      TV = 'TV'.freeze,

      # TODO: Write general description for TW
      TW = 'TW'.freeze,

      # TODO: Write general description for TZ
      TZ = 'TZ'.freeze,

      # TODO: Write general description for UA
      UA = 'UA'.freeze,

      # TODO: Write general description for UG
      UG = 'UG'.freeze,

      # TODO: Write general description for UM
      UM = 'UM'.freeze,

      # TODO: Write general description for US
      US = 'US'.freeze,

      # TODO: Write general description for UY
      UY = 'UY'.freeze,

      # TODO: Write general description for UZ
      UZ = 'UZ'.freeze,

      # TODO: Write general description for VA
      VA = 'VA'.freeze,

      # TODO: Write general description for VC
      VC = 'VC'.freeze,

      # TODO: Write general description for VE
      VE = 'VE'.freeze,

      # TODO: Write general description for VG
      VG = 'VG'.freeze,

      # TODO: Write general description for VI
      VI = 'VI'.freeze,

      # TODO: Write general description for VN
      VN = 'VN'.freeze,

      # TODO: Write general description for VU
      VU = 'VU'.freeze,

      # TODO: Write general description for WF
      WF = 'WF'.freeze,

      # TODO: Write general description for WS
      WS = 'WS'.freeze,

      # TODO: Write general description for YE
      YE = 'YE'.freeze,

      # TODO: Write general description for YT
      YT = 'YT'.freeze,

      # TODO: Write general description for ZA
      ZA = 'ZA'.freeze,

      # TODO: Write general description for ZM
      ZM = 'ZM'.freeze,

      # TODO: Write general description for ZW
      ZW = 'ZW'.freeze
    ].freeze
  end
end
