# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module Pqapiv2
  # Time at which the object was created.
  class CreatedOn < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Time at which the object was created.
    # @return [DateTime]
    attr_accessor :created_on

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['created_on'] = 'createdOn'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        created_on
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(created_on = nil)
      @created_on = created_on unless created_on == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      created_on = if hash.key?('createdOn')
                     (DateTimeHelper.from_rfc3339(hash['createdOn']) if hash['createdOn'])
                   else
                     SKIP
                   end

      # Create object from extracted values.
      CreatedOn.new(created_on)
    end

    def to_created_on
      DateTimeHelper.to_rfc3339(created_on)
    end
  end
end
