# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Currency code used for the object
  class Currency < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Currency code type for the object
    # @return [CurrencyTypesEnum]
    attr_accessor :currency

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['currency'] = 'currency'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        currency
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(currency = nil)
      @currency = currency unless currency == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      currency = hash.key?('currency') ? hash['currency'] : SKIP

      # Create object from extracted values.
      Currency.new(currency)
    end
  end
end
