# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Currency code type for the object
  class CurrencyTypesEnum
    CURRENCY_TYPES_ENUM = [
      # TODO: Write general description for USD
      USD = 'USD'.freeze,

      # TODO: Write general description for CAD
      CAD = 'CAD'.freeze,

      # TODO: Write general description for MXN
      MXN = 'MXN'.freeze,

      # TODO: Write general description for AUD
      AUD = 'AUD'.freeze,

      # TODO: Write general description for HKD
      HKD = 'HKD'.freeze,

      # TODO: Write general description for NZD
      NZD = 'NZD'.freeze,

      # TODO: Write general description for EUR
      EUR = 'EUR'.freeze,

      # TODO: Write general description for GBP
      GBP = 'GBP'.freeze
    ].freeze
  end
end
