# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Three- or four-digit Card Verification Value (CVV) number displayed on the
  # back of a credit or debit card
  class Cvv < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Card Verification Value (CVV) on the credit card or debit card. (3-digit
    # number on VISA®, MasterCard® branded credit and debit cards)
    # @return [String]
    attr_accessor :cvv

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['cvv'] = 'cvv'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        cvv
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(cvv = nil)
      @cvv = cvv unless cvv == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      cvv = hash.key?('cvv') ? hash['cvv'] : SKIP

      # Create object from extracted values.
      Cvv.new(cvv)
    end
  end
end
