# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Unique identifier representing the destination of funds.
  class DestinationToken < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique identifier representing the destination of funds.
    # @return [String]
    attr_accessor :destination_token

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['destination_token'] = 'destinationToken'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        destination_token
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(destination_token = nil)
      @destination_token = destination_token unless destination_token == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      destination_token =
        hash.key?('destinationToken') ? hash['destinationToken'] : SKIP

      # Create object from extracted values.
      DestinationToken.new(destination_token)
    end
  end
end
