# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Contact email address for the user account
  class EmailAddress < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Email address for the user account
    # @return [String]
    attr_accessor :email

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['email'] = 'email'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        email
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(email = nil)
      @email = email unless email == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      email = hash.key?('email') ? hash['email'] : SKIP

      # Create object from extracted values.
      EmailAddress.new(email)
    end
  end
end
