# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # format.
  class FormatEnum
    FORMAT_ENUM = [
      # TODO: Write general description for TEXT
      TEXT = 'TEXT'.freeze,

      # TODO: Write general description for IMAGE
      IMAGE = 'IMAGE'.freeze,

      # TODO: Write general description for ENUM_TEXTIMAGE
      ENUM_TEXTIMAGE = 'TEXT;IMAGE'.freeze
    ].freeze
  end
end
