# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Gender as a user identifies
  class GenderTypesEnum
    GENDER_TYPES_ENUM = [
      # TODO: Write general description for MALE
      MALE = 'MALE'.freeze,

      # TODO: Write general description for FEMALE
      FEMALE = 'FEMALE'.freeze,

      # TODO: Write general description for NOT_SPECIFIED
      NOT_SPECIFIED = 'NOT_SPECIFIED'.freeze
    ].freeze
  end
end
