# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Gender as the user identifies
  class Gender < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Gender as a user identifies
    # @return [GenderTypesEnum]
    attr_accessor :gender

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['gender'] = 'gender'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        gender
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(gender = nil)
      @gender = gender unless gender == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      gender = hash.key?('gender') ? hash['gender'] : SKIP

      # Create object from extracted values.
      Gender.new(gender)
    end
  end
end
