# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # User's government ID type
  class GovernmentIdTypeEnum
    GOVERNMENT_ID_TYPE_ENUM = [
      # TODO: Write general description for PASSPORT
      PASSPORT = 'PASSPORT'.freeze,

      # TODO: Write general description for NATIONAL_ID_CARD
      NATIONAL_ID_CARD = 'NATIONAL_ID_CARD'.freeze,

      # TODO: Write general description for CURP
      CURP = 'CURP'.freeze
    ].freeze
  end
end
