# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Indicates the HATEOS relationship between the target and current resources.
  class HaetosRelationship < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Indicates the relationship between the target and current resources.
    # @return [String]
    attr_accessor :rel

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['rel'] = 'rel'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(rel = 'self')
      @rel = rel unless rel == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      rel = hash['rel'] ||= 'self'

      # Create object from extracted values.
      HaetosRelationship.new(rel)
    end
  end
end
