# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Provider reference used for performing identity checks for the provider
  class IdentityVerificationProviderReference < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # IDV provider unique ID for the IDV check performed
    # @return [String]
    attr_accessor :idv_provider_reference

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['idv_provider_reference'] = 'idvProviderReference'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        idv_provider_reference
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(idv_provider_reference = nil)
      @idv_provider_reference = idv_provider_reference unless idv_provider_reference == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      idv_provider_reference =
        hash.key?('idvProviderReference') ? hash['idvProviderReference'] : SKIP

      # Create object from extracted values.
      IdentityVerificationProviderReference.new(idv_provider_reference)
    end
  end
end
