# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Provider type of verification that can be used for performing identity
  # checks
  class IdentityVerificationProviderType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Provider types of verification that can be used for performing identity
    # checks
    # @return [IdentityVerificationProviderTypesEnum]
    attr_accessor :idv_provider

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['idv_provider'] = 'idvProvider'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        idv_provider
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(idv_provider = nil)
      @idv_provider = idv_provider unless idv_provider == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      idv_provider = hash.key?('idvProvider') ? hash['idvProvider'] : SKIP

      # Create object from extracted values.
      IdentityVerificationProviderType.new(idv_provider)
    end
  end
end
