# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Provider types of verification that can be used for performing identity
  # checks
  class IdentityVerificationProviderTypesEnum
    IDENTITY_VERIFICATION_PROVIDER_TYPES_ENUM = [
      # TODO: Write general description for W2
      W2 = 'W2'.freeze,

      # TODO: Write general description for IDOLOGY
      IDOLOGY = 'IDOLOGY'.freeze,

      # TODO: Write general description for BANK
      BANK = 'BANK'.freeze,

      # TODO: Write general description for EQUIFAX
      EQUIFAX = 'EQUIFAX'.freeze,

      # TODO: Write general description for OFAC
      OFAC = 'OFAC'.freeze,

      # TODO: Write general description for LEXUS_NEXUS
      LEXUS_NEXUS = 'LEXUS_NEXUS'.freeze
    ].freeze
  end
end
