# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Type of verification used for performing an identity check
  class IdentityVerificationCheckType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Types of verification used for performing identity checks
    # (<i>documentary</i>, <i>non-documentary</i>, <i>OFAC</i>, etc.)
    # @return [IdentityVerificationCheckTypesEnum]
    attr_accessor :idv_check_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['idv_check_type'] = 'idvCheckType'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        idv_check_type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(idv_check_type = nil)
      @idv_check_type = idv_check_type unless idv_check_type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      idv_check_type = hash.key?('idvCheckType') ? hash['idvCheckType'] : SKIP

      # Create object from extracted values.
      IdentityVerificationCheckType.new(idv_check_type)
    end
  end
end
