# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # In combination with the <i>Disposition</i> type, the <i>Result</i> type
  # provides the results of an IDV check. A <i>Dispositioned</i> result of
  # <i>FINAL PASS</i> represents a passing check, whereas a <i>TRANSIENT
  # FAIL</i> is still being processed but has failed at least one phase of the
  # check. Until the disposition is <i>FINAL</i>, a result has not been
  # determined.
  class IdentityVerificationDispositionTypesEnum
    IDENTITY_VERIFICATION_DISPOSITION_TYPES_ENUM = [
      # TODO: Write general description for TRANSIENT
      TRANSIENT = 'TRANSIENT'.freeze,

      # TODO: Write general description for FINAL
      FINAL = 'FINAL'.freeze
    ].freeze
  end
end
