# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Types of verification used for performing identity checks
  # (<i>documentary</i>, <i>non-documentary</i>, <i>OFAC</i>, etc.)
  class IdentityVerificationCheckTypesEnum
    IDENTITY_VERIFICATION_CHECK_TYPES_ENUM = [
      # TODO: Write general description for DOCUMENTARY
      DOCUMENTARY = 'DOCUMENTARY'.freeze,

      # TODO: Write general description for NON_DOCUMENTARY
      NON_DOCUMENTARY = 'NON_DOCUMENTARY'.freeze,

      # TODO: Write general description for OFAC
      OFAC = 'OFAC'.freeze
    ].freeze
  end
end
