# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # In combination with the <i>Disposition</i> type, the <i>Result</i> type
  # provides the results of an IDV check. A <i>Dispositioned</i> result of
  # <i>FINAL PASS</i> represents a passing check, whereas a <i>TRANSIENT
  # FAIL</i> is still being processed but has failed at least one phase of the
  # check. Until the disposition is <i>FINAL</i>, a result has not been
  # determined.
  class IdentityVerificationDispositionType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # In combination with the <i>Disposition</i> type, the <i>Result</i> type
    # provides the results of an IDV check. A <i>Dispositioned</i> result of
    # <i>FINAL PASS</i> represents a passing check, whereas a <i>TRANSIENT
    # FAIL</i> is still being processed but has failed at least one phase of the
    # check. Until the disposition is <i>FINAL</i>, a result has not been
    # determined.
    # @return [IdentityVerificationDispositionTypesEnum]
    attr_accessor :idv_dispostion

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['idv_dispostion'] = 'idvDispostion'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        idv_dispostion
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(idv_dispostion = nil)
      @idv_dispostion = idv_dispostion unless idv_dispostion == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      idv_dispostion = hash.key?('idvDispostion') ? hash['idvDispostion'] : SKIP

      # Create object from extracted values.
      IdentityVerificationDispositionType.new(idv_dispostion)
    end
  end
end
