# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Language type in IETF's BCP 47 format
  class LanguageTypesEnum
    LANGUAGE_TYPES_ENUM = [
      # TODO: Write general description for ENUS
      ENUS = 'en-US'.freeze,

      # TODO: Write general description for ENGB
      ENGB = 'en-GB'.freeze,

      # TODO: Write general description for FRCA
      FRCA = 'fr-CA'.freeze,

      # TODO: Write general description for FRFR
      FRFR = 'fr-FR'.freeze,

      # TODO: Write general description for ESMX
      ESMX = 'es-MX'.freeze,

      # TODO: Write general description for ESES
      ESES = 'es-ES'.freeze,

      # TODO: Write general description for PTBR
      PTBR = 'pt-BR'.freeze,

      # TODO: Write general description for PTPT
      PTPT = 'pt-PT'.freeze,

      # TODO: Write general description for DEDE
      DEDE = 'de-DE'.freeze,

      # TODO: Write general description for ITIT
      ITIT = 'it-IT'.freeze,

      # TODO: Write general description for JAJP
      JAJP = 'ja-JP'.freeze,

      # TODO: Write general description for ZHCN
      ZHCN = 'zh-CN'.freeze,

      # TODO: Write general description for ZHTW
      ZHTW = 'zh-TW'.freeze
    ].freeze
  end
end
