# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Optional internal memo not visible to the user.
  class Memo < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Optional internal memo not visible to the user.
    # @return [String]
    attr_accessor :memo

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['memo'] = 'memo'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        memo
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(memo = nil)
      @memo = memo unless memo == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      memo = hash.key?('memo') ? hash['memo'] : SKIP

      # Create object from extracted values.
      Memo.new(memo)
    end
  end
end
