# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Namespace used to identify and refer to the object
  class NamespaceEnum
    NAMESPACE_ENUM = [
      # TODO: Write general description for
      # ENUM_BANKACCOUNTSUPDATEDSTATUSAPPROVED
      ENUM_BANKACCOUNTSUPDATEDSTATUSAPPROVED = 'BANKACCOUNTS.UPDATED.STATUS.APPROVED'.freeze,

      # TODO: Write general description for ENUM_PREPAIDCARDSCREATED
      ENUM_PREPAIDCARDSCREATED = 'PREPAIDCARDS.CREATED'.freeze,

      # TODO: Write general description for ENUM_TRANSFERSACCEPTED
      ENUM_TRANSFERSACCEPTED = 'TRANSFERS.ACCEPTED'.freeze
    ].freeze
  end
end
