# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Optional comments visible to the user
  class Notes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Optional comments visible to the user.
    # @return [String]
    attr_accessor :notes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['notes'] = 'notes'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        notes
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(notes = nil)
      @notes = notes unless notes == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      notes = hash.key?('notes') ? hash['notes'] : SKIP

      # Create object from extracted values.
      Notes.new(notes)
    end
  end
end
