# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Occupation Model.
  class Occupation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Type of occupation for the user
    # @return [OccupationTypesEnum]
    attr_accessor :occupation

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['occupation'] = 'occupation'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        occupation
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(occupation = nil)
      @occupation = occupation unless occupation == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      occupation = hash.key?('occupation') ? hash['occupation'] : SKIP

      # Create object from extracted values.
      Occupation.new(occupation)
    end
  end
end
