# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Type of occupation for the user
  class OccupationTypesEnum
    OCCUPATION_TYPES_ENUM = [
      # TODO: Write general description for INDEPENDENT_BUSINESS_OWNER
      INDEPENDENT_BUSINESS_OWNER = 'INDEPENDENT_BUSINESS_OWNER'.freeze,

      # TODO: Write general description for SCIENCE
      SCIENCE = 'SCIENCE'.freeze,

      # TODO: Write general description for TECHNOLOGY
      TECHNOLOGY = 'TECHNOLOGY'.freeze,

      # TODO: Write general description for ENGINEERING
      ENGINEERING = 'ENGINEERING'.freeze,

      # TODO: Write general description for MATH
      MATH = 'MATH'.freeze,

      # TODO: Write general description for HEALTHCARE
      HEALTHCARE = 'HEALTHCARE'.freeze,

      # TODO: Write general description for SOCIAL_SERVICES
      SOCIAL_SERVICES = 'SOCIAL_SERVICES'.freeze,

      # TODO: Write general description for MEDIA
      MEDIA = 'MEDIA'.freeze,

      # TODO: Write general description for FINANCE
      FINANCE = 'FINANCE'.freeze,

      # TODO: Write general description for GOVERNMENT
      GOVERNMENT = 'GOVERNMENT'.freeze,

      # TODO: Write general description for MANUFACTURING
      MANUFACTURING = 'MANUFACTURING'.freeze,

      # TODO: Write general description for LAW
      LAW = 'LAW'.freeze,

      # TODO: Write general description for HOSPITALITY_AND_TOURISM
      HOSPITALITY_AND_TOURISM = 'HOSPITALITY_AND_TOURISM'.freeze,

      # TODO: Write general description for ARTS
      ARTS = 'ARTS'.freeze,

      # TODO: Write general description for DESIGN
      DESIGN = 'DESIGN'.freeze,

      # TODO: Write general description for OFFICE_AND_ADMIN_SUPPORT
      OFFICE_AND_ADMIN_SUPPORT = 'OFFICE_AND_ADMIN_SUPPORT'.freeze,

      # TODO: Write general description for EDUCATION
      EDUCATION = 'EDUCATION'.freeze
    ].freeze
  end
end
