# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Used to identify the purpose of a payment and impacts reporting and
  # calculated taxable earnings (if utilizing tax services)
  class PaymentPurposeTypesEnum
    PAYMENT_PURPOSE_TYPES_ENUM = [
      # TODO: Write general description for OTHER
      OTHER = 'OTHER'.freeze,

      # TODO: Write general description for TAXABLE
      TAXABLE = 'TAXABLE'.freeze,

      # TODO: Write general description for INCOME
      INCOME = 'INCOME'.freeze,

      # TODO: Write general description for BONUS
      BONUS = 'BONUS'.freeze,

      # TODO: Write general description for EXPENSE
      EXPENSE = 'EXPENSE'.freeze,

      # TODO: Write general description for NON_TAXABLE
      NON_TAXABLE = 'NON_TAXABLE'.freeze
    ].freeze
  end
end
