# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Specifies a card is <i>Personalized</i> or <i>Non-personalized</i> (i.e.,
  # issued to Preferred Customer)
  class PrepaidCardPersonalizationTypesEnum
    PREPAID_CARD_PERSONALIZATION_TYPES_ENUM = [
      # TODO: Write general description for PERSONALIZED
      PERSONALIZED = 'PERSONALIZED'.freeze,

      # TODO: Write general description for NON_PERSONALIZED
      NON_PERSONALIZED = 'NON_PERSONALIZED'.freeze
    ].freeze
  end
end
