# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Reason for card replacement. In certain programs, the replacement reason
  # code impacts replacement cost and responsibility.
  class PrepaidCardReplacementReasonTypesEnum
    PREPAID_CARD_REPLACEMENT_REASON_TYPES_ENUM = [
      # TODO: Write general description for LOST
      LOST = 'LOST'.freeze,

      # TODO: Write general description for STOLEN
      STOLEN = 'STOLEN'.freeze,

      # TODO: Write general description for DAMAGED
      DAMAGED = 'DAMAGED'.freeze,

      # TODO: Write general description for COMPROMISED
      COMPROMISED = 'COMPROMISED'.freeze,

      # TODO: Write general description for EXPIRED
      EXPIRED = 'EXPIRED'.freeze
    ].freeze
  end
end
