# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # PrepaidCardReplacementReason Model.
  class PrepaidCardReplacementReason < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Reason for card replacement. In certain programs, the replacement reason
    # code impacts replacement cost and responsibility.
    # @return [PrepaidCardReplacementReasonTypesEnum]
    attr_accessor :card_replacement_reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_replacement_reason'] = 'cardReplacementReason'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        card_replacement_reason
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(card_replacement_reason = nil)
      @card_replacement_reason = card_replacement_reason unless card_replacement_reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_replacement_reason =
        hash.key?('cardReplacementReason') ? hash['cardReplacementReason'] : SKIP

      # Create object from extracted values.
      PrepaidCardReplacementReason.new(card_replacement_reason)
    end
  end
end
