# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # PrepaidCardReplacementBase Model.
  class PrepaidCardReplacementBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Package for the card being displayed (<i>Virtual<,i>) or <i>Produced
    # (physical)</i>
    # @return [String]
    attr_accessor :card_package

    # Token representing a program
    # @return [String]
    attr_accessor :program_token

    # Reason for card replacement. In certain programs, the replacement reason
    # code impacts replacement cost and responsibility.
    # @return [PrepaidCardReplacementReasonTypesEnum]
    attr_accessor :card_replacement_reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_package'] = 'cardPackage'
      @_hash['program_token'] = 'programToken'
      @_hash['card_replacement_reason'] = 'cardReplacementReason'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        card_package
        card_replacement_reason
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(program_token = nil,
                   card_package = nil,
                   card_replacement_reason = nil)
      @card_package = card_package unless card_package == SKIP
      @program_token = program_token unless program_token == SKIP
      @card_replacement_reason = card_replacement_reason unless card_replacement_reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      program_token = hash.key?('programToken') ? hash['programToken'] : SKIP
      card_package = hash.key?('cardPackage') ? hash['cardPackage'] : SKIP
      card_replacement_reason =
        hash.key?('cardReplacementReason') ? hash['cardReplacementReason'] : SKIP

      # Create object from extracted values.
      PrepaidCardReplacementBase.new(program_token,
                                     card_package,
                                     card_replacement_reason)
    end
  end
end
