# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # PrepaidCardPinToken Model.
  class PrepaidCardPinToken < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token used as part of a two-leg card PIN reveal request sent directly from
    # the client that generally involves a second piece of data, such as the CVV
    # code on the back of the card.
    # @return [String]
    attr_accessor :card_pin_token

    # Full path of the URI to perform the request action against a prepaid card
    # that replaces the need to build the URL with query params
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_pin_token'] = 'cardPinToken'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        card_pin_token
        url
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(card_pin_token = nil,
                   url = nil)
      @card_pin_token = card_pin_token unless card_pin_token == SKIP
      @url = url unless url == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_pin_token = hash.key?('cardPinToken') ? hash['cardPinToken'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create object from extracted values.
      PrepaidCardPinToken.new(card_pin_token,
                              url)
    end
  end
end
