# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # PrepaidCardDataTokenResponse Model.
  class PrepaidCardDataTokenResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token assigned to the prepaid card
    # @return [PrepaidCardDataToken]
    attr_accessor :token

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token'] = 'token'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        token
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(token = nil)
      @token = token unless token == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token = PrepaidCardDataToken.from_hash(hash['token']) if hash['token']

      # Create object from extracted values.
      PrepaidCardDataTokenResponse.new(token)
    end
  end
end
