# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Package for the card being displayed (<i>Virtual<,i>) or <i>Produced
  # (physical)</i>, including artwork, packaging, and delivery method
  class PrepaidCardPackage < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Package for the card being displayed (<i>Virtual<,i>) or <i>Produced
    # (physical)</i>
    # @return [String]
    attr_accessor :card_package

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['card_package'] = 'cardPackage'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        card_package
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(card_package = nil)
      @card_package = card_package unless card_package == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      card_package = hash.key?('cardPackage') ? hash['cardPackage'] : SKIP

      # Create object from extracted values.
      PrepaidCardPackage.new(card_package)
    end
  end
end
