# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Program identifier for the user
  class ProgramUserId < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Program identifier for the user
    # @return [String]
    attr_accessor :program_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['program_user_id'] = 'programUserId'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        program_user_id
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(program_user_id = nil)
      @program_user_id = program_user_id unless program_user_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      program_user_id =
        hash.key?('programUserId') ? hash['programUserId'] : SKIP

      # Create object from extracted values.
      ProgramUserId.new(program_user_id)
    end
  end
end
