# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Exchange rate
  class Rate < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Exchange rate
    # @return [Float]
    attr_accessor :rate

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['rate'] = 'rate'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        rate
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(rate = nil)
      @rate = rate unless rate == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      rate = hash.key?('rate') ? hash['rate'] : SKIP

      # Create object from extracted values.
      Rate.new(rate)
    end
  end
end
