# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Shipping method type for a pre-paid card or paper check
  class ShippingMethodTypesEnum
    SHIPPING_METHOD_TYPES_ENUM = [
      # TODO: Write general description for STANDARD
      STANDARD = 'STANDARD'.freeze,

      # TODO: Write general description for EXPEDITED
      EXPEDITED = 'EXPEDITED'.freeze
    ].freeze
  end
end
