# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Shipping method desired
  class ShippingMethod < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Shipping method type for a pre-paid card or paper check
    # @return [ShippingMethodTypesEnum]
    attr_accessor :shipping_method

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['shipping_method'] = 'shippingMethod'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        shipping_method
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(shipping_method = nil)
      @shipping_method = shipping_method unless shipping_method == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      shipping_method =
        hash.key?('shippingMethod') ? hash['shippingMethod'] : SKIP

      # Create object from extracted values.
      ShippingMethod.new(shipping_method)
    end
  end
end
