# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # side.
  class SideEnum
    SIDE_ENUM = [
      # TODO: Write general description for FRONT
      FRONT = 'FRONT'.freeze,

      # TODO: Write general description for BACK
      BACK = 'BACK'.freeze
    ].freeze
  end
end
