# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Required details of the monetary source.
  class SourceMonetaryRequired < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Amount of the transfer in the specified currency.
    # @return [Float]
    attr_accessor :source_amount

    # Currency code type for the object
    # @return [CurrencyTypesEnum]
    attr_accessor :source_currency

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source_amount'] = 'sourceAmount'
      @_hash['source_currency'] = 'sourceCurrency'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        source_amount
        source_currency
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(source_amount = nil,
                   source_currency = nil)
      @source_amount = source_amount unless source_amount == SKIP
      @source_currency = source_currency unless source_currency == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source_amount = hash.key?('sourceAmount') ? hash['sourceAmount'] : SKIP
      source_currency =
        hash.key?('sourceCurrency') ? hash['sourceCurrency'] : SKIP

      # Create object from extracted values.
      SourceMonetaryRequired.new(source_amount,
                                 source_currency)
    end
  end
end
