# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Current status of the prepaid card
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for QUEUED
      QUEUED = 'QUEUED'.freeze,

      # TODO: Write general description for LOST_STOLEN_DAMAGED
      LOST_STOLEN_DAMAGED = 'LOST_STOLEN_DAMAGED'.freeze,

      # TODO: Write general description for ACTIVATED
      ACTIVATED = 'ACTIVATED'.freeze,

      # TODO: Write general description for PENDING_ACTIVATION
      PENDING_ACTIVATION = 'PENDING_ACTIVATION'.freeze,

      # TODO: Write general description for SUSPENDED
      SUSPENDED = 'SUSPENDED'.freeze,

      # TODO: Write general description for COMPLIANCE_HOLD
      COMPLIANCE_HOLD = 'COMPLIANCE_HOLD'.freeze,

      # TODO: Write general description for KYC_HOLD
      KYC_HOLD = 'KYC_HOLD'.freeze,

      # TODO: Write general description for LOCKED
      LOCKED = 'LOCKED'.freeze
    ].freeze
  end
end
