# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Tax resident status type of a country
  class TaxResidentStatusTypesEnum
    TAX_RESIDENT_STATUS_TYPES_ENUM = [
      # TODO: Write general description for YES
      YES = 'YES'.freeze,

      # TODO: Write general description for NO
      NO = 'NO'.freeze,

      # TODO: Write general description for PREFER_NOT_TO_ANSWER
      PREFER_NOT_TO_ANSWER = 'PREFER_NOT_TO_ANSWER'.freeze
    ].freeze
  end
end
