# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Types of resources represented by a token
  class TokenTypesEnum
    TOKEN_TYPES_ENUM = [
      # TODO: Write general description for BANK_ACCOUNT
      BANK_ACCOUNT = 'BANK_ACCOUNT'.freeze,

      # TODO: Write general description for TRANSFER
      TRANSFER = 'TRANSFER'.freeze,

      # TODO: Write general description for PAYMENT
      PAYMENT = 'PAYMENT'.freeze,

      # TODO: Write general description for SPEND_BACK
      SPEND_BACK = 'SPEND_BACK'.freeze,

      # TODO: Write general description for PREPAID_CARD
      PREPAID_CARD = 'PREPAID_CARD'.freeze,

      # TODO: Write general description for USER
      USER = 'USER'.freeze,

      # TODO: Write general description for DOCUMENT
      DOCUMENT = 'DOCUMENT'.freeze,

      # TODO: Write general description for ACCOUNT
      ACCOUNT = 'ACCOUNT'.freeze
    ].freeze
  end
end
