# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # TokenType Model.
  class TokenType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Types of resources represented by a token
    # @return [TokenTypesEnum]
    attr_accessor :token_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['token_type'] = 'tokenType'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        token_type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(token_type = nil)
      @token_type = token_type unless token_type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      token_type = hash.key?('tokenType') ? hash['tokenType'] : SKIP

      # Create object from extracted values.
      TokenType.new(token_type)
    end
  end
end
