# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Request for the transfer
  class TransferRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique identifier representing the source of funds.
    # @return [String]
    attr_accessor :source_token

    # Unique identifier representing the destination of funds.
    # @return [String]
    attr_accessor :destination_token

    # Optional comments visible to the user.
    # @return [String]
    attr_accessor :notes

    # Optional internal memo not visible to the user.
    # @return [String]
    attr_accessor :memo

    # Unique value provided by the client for the transfer.
    # @return [String]
    attr_accessor :client_transfer_id

    # Amount transferred to the destination
    # @return [Float]
    attr_accessor :destination_amount

    # Currency code type for the object
    # @return [CurrencyTypesEnum]
    attr_accessor :destination_currency

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source_token'] = 'sourceToken'
      @_hash['destination_token'] = 'destinationToken'
      @_hash['notes'] = 'notes'
      @_hash['memo'] = 'memo'
      @_hash['client_transfer_id'] = 'clientTransferId'
      @_hash['destination_amount'] = 'destinationAmount'
      @_hash['destination_currency'] = 'destinationCurrency'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        source_token
        destination_token
        notes
        memo
        client_transfer_id
        destination_amount
        destination_currency
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(source_token = nil,
                   destination_token = nil,
                   notes = nil,
                   memo = nil,
                   client_transfer_id = nil,
                   destination_amount = nil,
                   destination_currency = nil)
      @source_token = source_token unless source_token == SKIP
      @destination_token = destination_token unless destination_token == SKIP
      @notes = notes unless notes == SKIP
      @memo = memo unless memo == SKIP
      @client_transfer_id = client_transfer_id unless client_transfer_id == SKIP
      @destination_amount = destination_amount unless destination_amount == SKIP
      @destination_currency = destination_currency unless destination_currency == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source_token = hash.key?('sourceToken') ? hash['sourceToken'] : SKIP
      destination_token =
        hash.key?('destinationToken') ? hash['destinationToken'] : SKIP
      notes = hash.key?('notes') ? hash['notes'] : SKIP
      memo = hash.key?('memo') ? hash['memo'] : SKIP
      client_transfer_id =
        hash.key?('clientTransferId') ? hash['clientTransferId'] : SKIP
      destination_amount =
        hash.key?('destinationAmount') ? hash['destinationAmount'] : SKIP
      destination_currency =
        hash.key?('destinationCurrency') ? hash['destinationCurrency'] : SKIP

      # Create object from extracted values.
      TransferRequest.new(source_token,
                          destination_token,
                          notes,
                          memo,
                          client_transfer_id,
                          destination_amount,
                          destination_currency)
    end
  end
end
