# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Base class for the transfer
  class TransferBase < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique identifier representing the source of funds.
    # @return [String]
    attr_accessor :source_token

    # Unique identifier representing the destination of funds.
    # @return [String]
    attr_accessor :destination_token

    # Optional comments visible to the user.
    # @return [String]
    attr_accessor :notes

    # Optional internal memo not visible to the user.
    # @return [String]
    attr_accessor :memo

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['source_token'] = 'sourceToken'
      @_hash['destination_token'] = 'destinationToken'
      @_hash['notes'] = 'notes'
      @_hash['memo'] = 'memo'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        source_token
        destination_token
        notes
        memo
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(source_token = nil,
                   destination_token = nil,
                   notes = nil,
                   memo = nil)
      @source_token = source_token unless source_token == SKIP
      @destination_token = destination_token unless destination_token == SKIP
      @notes = notes unless notes == SKIP
      @memo = memo unless memo == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      source_token = hash.key?('sourceToken') ? hash['sourceToken'] : SKIP
      destination_token =
        hash.key?('destinationToken') ? hash['destinationToken'] : SKIP
      notes = hash.key?('notes') ? hash['notes'] : SKIP
      memo = hash.key?('memo') ? hash['memo'] : SKIP

      # Create object from extracted values.
      TransferBase.new(source_token,
                       destination_token,
                       notes,
                       memo)
    end
  end
end
