# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Type of transfer method
  class TransferType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Transfer type
    # @return [TransferTypesEnum]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(type = nil)
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      TransferType.new(type)
    end
  end
end
