# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Transfer type
  class TransferTypesEnum
    TRANSFER_TYPES_ENUM = [
      # TODO: Write general description for PAPER_CHECK
      PAPER_CHECK = 'PAPER_CHECK'.freeze,

      # TODO: Write general description for BANK_TRANSFER
      BANK_TRANSFER = 'BANK_TRANSFER'.freeze,

      # TODO: Write general description for PAYMENT
      PAYMENT = 'PAYMENT'.freeze,

      # TODO: Write general description for SPEND_BACK
      SPEND_BACK = 'SPEND_BACK'.freeze
    ].freeze
  end
end
