# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Current status of a transfer
  class TransferStatusTypesEnum
    TRANSFER_STATUS_TYPES_ENUM = [
      # TODO: Write general description for QUOTED
      QUOTED = 'QUOTED'.freeze,

      # TODO: Write general description for PENDING
      PENDING = 'PENDING'.freeze,

      # TODO: Write general description for SCHEDULED
      SCHEDULED = 'SCHEDULED'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'COMPLETED'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'CANCELLED'.freeze,

      # TODO: Write general description for RETURNED
      RETURNED = 'RETURNED'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze,

      # TODO: Write general description for EXPIRED
      EXPIRED = 'EXPIRED'.freeze,

      # TODO: Write general description for VERIFICATION_HOLD
      VERIFICATION_HOLD = 'VERIFICATION_HOLD'.freeze
    ].freeze
  end
end
