# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # UserKycInformation Model.
  class UserKycInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # User's driver's license number
    # @return [String]
    attr_accessor :driver_license_id

    # User's passport number
    # @return [String]
    attr_accessor :passport_id

    # User's government ID type
    # @return [GovernmentIdTypeEnum]
    attr_accessor :government_id_type

    # User's government ID number, such as a <i>SSN</i>, <i>EIN</i>, or
    # <i>SIN</i>
    # @return [String]
    attr_accessor :government_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['driver_license_id'] = 'driverLicenseId'
      @_hash['passport_id'] = 'passportId'
      @_hash['government_id_type'] = 'governmentIdType'
      @_hash['government_id'] = 'governmentId'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        driver_license_id
        passport_id
        government_id_type
        government_id
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(driver_license_id = nil,
                   passport_id = nil,
                   government_id_type = nil,
                   government_id = nil)
      @driver_license_id = driver_license_id unless driver_license_id == SKIP
      @passport_id = passport_id unless passport_id == SKIP
      @government_id_type = government_id_type unless government_id_type == SKIP
      @government_id = government_id unless government_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      driver_license_id =
        hash.key?('driverLicenseId') ? hash['driverLicenseId'] : SKIP
      passport_id = hash.key?('passportId') ? hash['passportId'] : SKIP
      government_id_type =
        hash.key?('governmentIdType') ? hash['governmentIdType'] : SKIP
      government_id = hash.key?('governmentId') ? hash['governmentId'] : SKIP

      # Create object from extracted values.
      UserKycInformation.new(driver_license_id,
                             passport_id,
                             government_id_type,
                             government_id)
    end
  end
end
