# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # UsersPrepaidCardsPinResponse Model.
  class UsersPrepaidCardsPinResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :result

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['result'] = 'result'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        result
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(result = nil)
      @result = result unless result == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      result = hash.key?('result') ? hash['result'] : SKIP

      # Create object from extracted values.
      UsersPrepaidCardsPinResponse.new(result)
    end
  end
end
