# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # User's profile type
  class UserType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account holder's profile type
    # @return [UserTypesEnum]
    attr_accessor :user_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['user_type'] = 'userType'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        user_type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(user_type = nil)
      @user_type = user_type unless user_type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      user_type = hash.key?('userType') ? hash['userType'] : SKIP

      # Create object from extracted values.
      UserType.new(user_type)
    end
  end
end
