# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Account holder's profile type
  class UserTypesEnum
    USER_TYPES_ENUM = [
      # TODO: Write general description for INDIVIDUAL
      INDIVIDUAL = 'INDIVIDUAL'.freeze,

      # TODO: Write general description for BUSINESS
      BUSINESS = 'BUSINESS'.freeze
    ].freeze
  end
end
