# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # UserName Model.
  class UserName < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # User's first name. <i>Required</i> if the user is registered as an
    # individual.
    # @return [String]
    attr_accessor :first_name

    # User's last name. <i>Required</i> if the user is registered as an
    # individual.
    # @return [String]
    attr_accessor :last_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first_name'] = 'firstName'
      @_hash['last_name'] = 'lastName'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        first_name
        last_name
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(first_name = nil,
                   last_name = nil)
      @first_name = first_name unless first_name == SKIP
      @last_name = last_name unless last_name == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      first_name = hash.key?('firstName') ? hash['firstName'] : SKIP
      last_name = hash.key?('lastName') ? hash['lastName'] : SKIP

      # Create object from extracted values.
      UserName.new(first_name,
                   last_name)
    end
  end
end
