# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Current status of the user
  class UserStatusTypesEnum
    USER_STATUS_TYPES_ENUM = [
      # TODO: Write general description for ACTIVATED
      ACTIVATED = 'ACTIVATED'.freeze,

      # TODO: Write general description for PRE_ACTIVATED
      PRE_ACTIVATED = 'PRE_ACTIVATED'.freeze,

      # TODO: Write general description for PENDING_EMAIL_VERIFICATION
      PENDING_EMAIL_VERIFICATION = 'PENDING_EMAIL_VERIFICATION'.freeze,

      # TODO: Write general description for PENDING_KYC
      PENDING_KYC = 'PENDING_KYC'.freeze
    ].freeze
  end
end
