# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # _validatorTypes.
  class ValidatorTypesEnum
    VALIDATOR_TYPES_ENUM = [
      # TODO: Write general description for REGEX
      REGEX = 'REGEX'.freeze,

      # TODO: Write general description for LENGTH
      LENGTH = 'LENGTH'.freeze
    ].freeze
  end
end
