# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Webhook Subscription collection response
  class WebhookCollectionResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [List of HaetosParams]
    attr_accessor :links

    # TODO: Write general description for this method
    # @return [List of WebhookSubscriptionResponse]
    attr_accessor :payload

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['links'] = 'links'
      @_hash['payload'] = 'payload'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        links
        payload
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(links = nil,
                   payload = nil)
      @links = links unless links == SKIP
      @payload = payload unless payload == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (HaetosParams.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')
      # Parameter is an array, so we need to iterate through it
      payload = nil
      unless hash['payload'].nil?
        payload = []
        hash['payload'].each do |structure|
          payload << (WebhookSubscriptionResponse.from_hash(structure) if structure)
        end
      end

      payload = SKIP unless hash.key?('payload')

      # Create object from extracted values.
      WebhookCollectionResponse.new(links,
                                    payload)
    end
  end
end
