# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Webhook subscription object
  class WebhookSubscription < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # Namespace used to identify and refer to the object
    # @return [NamespaceEnum]
    attr_accessor :namespace

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['url'] = 'url'
      @_hash['namespace'] = 'namespace'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        url
        namespace
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(url = nil,
                   namespace = nil)
      @url = url unless url == SKIP
      @namespace = namespace unless namespace == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      url = hash.key?('url') ? hash['url'] : SKIP
      namespace = hash.key?('namespace') ? hash['namespace'] : SKIP

      # Create object from extracted values.
      WebhookSubscription.new(url,
                              namespace)
    end
  end
end
