# pqapiv2
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Pqapiv2
  # Webhook Subscription response
  class WebhookSubscriptionResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [List of HaetosParams]
    attr_accessor :links

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # Namespace used to identify and refer to the object
    # @return [NamespaceEnum]
    attr_accessor :namespace

    # Token for the webhook subscription
    # @return [String]
    attr_accessor :token

    # Time stamp for the date the webhook subscription was created
    # @return [String]
    attr_accessor :created

    # Time stamp for the date the webhook subscription was updated
    # @return [String]
    attr_accessor :last_updated

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['links'] = 'links'
      @_hash['url'] = 'url'
      @_hash['namespace'] = 'namespace'
      @_hash['token'] = 'token'
      @_hash['created'] = 'created'
      @_hash['last_updated'] = 'lastUpdated'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        links
        url
        namespace
        token
        created
        last_updated
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(links = nil,
                   url = nil,
                   namespace = nil,
                   token = nil,
                   created = nil,
                   last_updated = nil)
      @links = links unless links == SKIP
      @url = url unless url == SKIP
      @namespace = namespace unless namespace == SKIP
      @token = token unless token == SKIP
      @created = created unless created == SKIP
      @last_updated = last_updated unless last_updated == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      links = nil
      unless hash['links'].nil?
        links = []
        hash['links'].each do |structure|
          links << (HaetosParams.from_hash(structure) if structure)
        end
      end

      links = SKIP unless hash.key?('links')
      url = hash.key?('url') ? hash['url'] : SKIP
      namespace = hash.key?('namespace') ? hash['namespace'] : SKIP
      token = hash.key?('token') ? hash['token'] : SKIP
      created = hash.key?('created') ? hash['created'] : SKIP
      last_updated = hash.key?('lastUpdated') ? hash['lastUpdated'] : SKIP

      # Create object from extracted values.
      WebhookSubscriptionResponse.new(links,
                                      url,
                                      namespace,
                                      token,
                                      created,
                                      last_updated)
    end
  end
end
